[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "simple-app"
version = "0.1.0"
requires-python = ">=3.11"

[project.scripts]
simple-app = "main:main"

[tool.setuptools]
py-modules = ["main"]